# Generated by Django 3.1.7 on 2022-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_auto_20220929_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
